apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  MONGO_LINK: mongodb+srv://jeyashreenirmalvasanpadmapriya_db_user:Mongopw261997@clustermern.84ywg7f.mongodb.net/streamingapp?retryWrites=true&w=majority
  JWS_PASS: changeme
  AWS_KEY_ID: replace
  AWS_ACCESS_KEY: replace