apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.type }}
  selector:
    component: frontend
  ports:
    - protocol: TCP
      port: 80          # cluster port
      targetPort: 80  # container port React is listening on
