apiVersion: v1
kind: Service
metadata:
  name: streamingservice
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.type }}
  selector:
    component: streamingservice
  ports:
    - protocol: TCP
      port: 3002        # cluster port
      targetPort: 3002
